### ISSUE TITLE
raise TranslationUnitLoadError("Error parsing translation unit.")    

### ISSUE THREAD

**Issue by teto** [arakashic/chromatica.nvim#19]
Hi,

This is my first attempt at using chromatica, I have a compile_commands.json which was in a ROOT/build folder, I moved it to the ROOT folder and then opened a file in ROOT/examples/ in neovim:

Here is an error in neovim :messages, I was wondering if it were normal ? I have no semantic highlighting.

```
error caught in async handler 'chromatica_highlight [{'filetype': 'cpp', 'filename': '/home/teto/dce2/example/dce-iperf.cc', 'buffer': <
neovim.api.buffer.Buffer object at 0x7f6393d320f0>, 'position': [27, 1], 'range': [1, 58], 'bufnr': 5, 'highlight_tick': 1, 'changedtick
': 2, 'args': ['-std=c++11', '-g', '-std=c++11', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-I
/home/teto/dce2/build/include', '-I/home/teto/dce2/include', '-I/home/teto/ns3off/install/include/ns3-dev', '-I/usr/include/gtk-2.0', '-
I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/
include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/libpng12', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/harfbuzz', '-I/
usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_LOG_
ENABLE', '-DNS3_ASSERT_ENABLE', '-DHAVE_STDINT_H=1', '-DHAVE_INTTYPES_H=1', '-DHAVE_SYS_TYPES_H=1', '-DHAVE_SYS_STAT_H=1', '-DHAVE_DIREN
T_H=1', '-DHAVE_GETCPUFEATURES=1', '-DHAVE_VALGRIND_VALGRIND_H=1', '-DHAVE_VALGRIND_MEMCHECK_H=1', '-DHAVE_SIM_H=1', '-DKERNEL_STACK=Y',
 '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1',
 '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_NS3_CORE=1', '-DHAVE_NS3_INTERNET=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_POINT_TO_POINT=1',
 '-DHAVE_SQLITE3=1', '-DHAVE_NS3_NETANIM=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_CSMA=1', '-DHAVE_SQLIT
E3=1', '-DHAVE_NS3_NETWORK=1', '-DHAVE_SQLITE3=1', '../example/dce-iperf.cc'], 'rpc': 'chromatica_highlight'}]'                         
Traceback (most recent call last):                                                                                                      
  File "/home/teto/.config/nvim/plugged/chromatica.nvim/rplugin/python3/chromatica/__init__.py", line 33, in highlight                  
    self.__chromatica.highlight(context)                                                                                                
  File "/home/teto/.config/nvim/plugged/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 197, in highlight               
    if filename not in self.ctx: return self.parse(context)                                                                             
  File "/home/teto/.config/nvim/plugged/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 99, in parse                    
    options=self.parse_options)                                                                                                         
  File "/home/teto/.config/nvim/plugged/chromatica.nvim/rplugin/python3/clang/cindex.py", line 2533, in parse                           
    self)                                                                                                                               
  File "/home/teto/.config/nvim/plugged/chromatica.nvim/rplugin/python3/clang/cindex.py", line 2665, in from_source                     
    raise TranslationUnitLoadError("Error parsing translation unit.")                                                                   
clang.cindex.TranslationUnitLoadError: Error parsing translation unit.  
```

Here is the log, it doesn't say that it found my compile_commands.json - IMO it should -  but it did as the flags are good:

```
2016-08-21 02:25:42,274 INFO     (chromatica.logging) --- Chromatica Log Start ---
2016-08-21 02:25:42,275 INFO     (chromatica.logging) NVIM v0.1.5-777-gae6db26, Python 3.5.2, neovim client 0.1.9
2016-08-21 02:26:53,185 DEBUG    (chromatica.core) filename: /home/teto/dce2/example/dce-iperf.cc
2016-08-21 02:26:53,188 INFO     (chromatica.core) args: ['-std=c++11', '-g', '-std=c++11', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-I/home/teto/dce2/build/include', '-I/home/teto/dce2/include', '-I/home/teto/ns3off/install/include/ns3-dev', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/libpng12', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_LOG_ENABLE', '-DNS3_ASSERT_ENABLE', '-DHAVE_STDINT_H=1', '-DHAVE_INTTYPES_H=1', '-DHAVE_SYS_TYPES_H=1', '-DHAVE_SYS_STAT_H=1', '-DHAVE_DIRENT_H=1', '-DHAVE_GETCPUFEATURES=1', '-DHAVE_VALGRIND_VALGRIND_H=1', '-DHAVE_VALGRIND_MEMCHECK_H=1', '-DHAVE_SIM_H=1', '-DKERNEL_STACK=Y', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_NS3_CORE=1', '-DHAVE_NS3_INTERNET=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_POINT_TO_POINT=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_NETANIM=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_CSMA=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_NETWORK=1', '-DHAVE_SQLITE3=1', '../example/dce-iperf.cc']
2016-08-21 02:26:53,195 DEBUG    (chromatica.core) {'filetype': 'cpp', 'filename': '/home/teto/dce2/example/dce-iperf.cc', 'buffer': <neovim.api.buffer.Buffer object at 0x7f6393d320f0>, 'position': [27, 1], 'range': [1, 58], 'bufnr': 5, 'highlight_tick': 1, 'changedtick': 2, 'args': ['-std=c++11', '-g', '-std=c++11', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-I/home/teto/dce2/build/include', '-I/home/teto/dce2/include', '-I/home/teto/ns3off/install/include/ns3-dev', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/libpng12', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/freetype2', '-I/usr/include/libxml2', '-DNS3_LOG_ENABLE', '-DNS3_ASSERT_ENABLE', '-DHAVE_STDINT_H=1', '-DHAVE_INTTYPES_H=1', '-DHAVE_SYS_TYPES_H=1', '-DHAVE_SYS_STAT_H=1', '-DHAVE_DIRENT_H=1', '-DHAVE_GETCPUFEATURES=1', '-DHAVE_VALGRIND_VALGRIND_H=1', '-DHAVE_VALGRIND_MEMCHECK_H=1', '-DHAVE_SIM_H=1', '-DKERNEL_STACK=Y', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYEMBED=1', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_NS3_CORE=1', '-DHAVE_NS3_INTERNET=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_POINT_TO_POINT=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_NETANIM=1', '-DHAVE_GTK2=1', '-DHAVE_LIBXML2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_CSMA=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_NETWORK=1', '-DHAVE_SQLITE3=1', '../example/dce-iperf.cc'], 'rpc': 'chromatica_highlight'}
```

Really excited by this plugin, thanks for your job so far

**Comment by arakashic** [comment]
This most likely be libclang is complaining about the args. I think it is `../example/dce-iperf.cc` (the last one in the list) that causes the failure. Chromatica is already passing the buffer content to clang. Clang will complain if the source file path is also passed in the args.

I think remove the path from args will solve the problem.

Please also check your Chromatic is the latest version. There is a recent patch for parsing `compile_commands.json` which should automatically take care of this problem.

**Comment by teto** [comment]
I am running latest chromatica and you are right that was the problem. Removing "../example/dce-iperf.cc" allowed chromatica to run ok and this is very cool :D

My compile_commands.json is generated by waf (https://waf.io/) so I suppose it is pretty standard, it would be nice if that worked out of the box, as it does for YCM.

**Comment by arakashic** [comment]
Sure. I can look at it. Unfortunately, the handling of compile_commands.json in chromatica is still is a pretty bad shape. :)

**Comment by arakashic** [comment]
@teto Hi, I have just pushed a fix to the `master` branch. I think I would also fix the problem that you were experiencing.
