### ISSUE TITLE
6d374fb ("Update libclang bindings") breaks Chromatica

### ISSUE THREAD

**Issue by pierremoreau** [arakashic/chromatica.nvim#30]
After updating to the latest HEAD (8f89c0d) on master, I get the following error message:

```
error caught in async handler 'chromatica_highlight [{'filename': '/home/pmoreau/teaching/LU_Computer_Graphics_Labs/src/core/opengl.cpp', 'position': [1, 1], 'highlight_tick': 1, 'range': [1, 88], 'filetype': 'cpp', 'rpc': 'chromatica_highlight', 'args': ['/usr/bin/clang++', '-DGLFW_DLL', '-I/home/pmoreau/privat/bui
ld/LU_Computer_Graphics_Labs/imgui/include', '-I/home/pmoreau/privat/build/LU_Computer_Graphics_Labs/imgui/include', '-I/home/pmoreau/teaching/LU_Computer_Graphics_Labs/src', '-I/home/pmoreau/teaching/LU_Computer_Graphics_Labs/src', '-I/home/pmoreau/teaching/LU_Computer_Graphics_Labs/src/external', '-I/home/pmoreau/
teaching/LU_Computer_Graphics_Labs/src/external', '-g', '-std=c++14'], 'tu': <clang.cindex.TranslationUnit object at 0x7fe00ebfbdd8>, 'buffer': <neovim.api.buffer.Buffer object at 0x7fe00ebefc50>, 'bufnr': 1, 'changedtick': 3}]'
Traceback (most recent call last):
  File "/home/pmoreau/privat/dotfiles/config/nvim/plugged/chromatica.nvim/rplugin/python3/chromatica/__init__.py", line 33, in highlight
    self.__chromatica.highlight(context)
  File "/home/pmoreau/privat/dotfiles/config/nvim/plugged/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 198, in highlight
    if filename not in self.ctx: return self.parse(context)
  File "/home/pmoreau/privat/dotfiles/config/nvim/plugged/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 115, in parse
    self.highlight(context) # update highlight on entire file
  File "/home/pmoreau/privat/dotfiles/config/nvim/plugged/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 202, in highlight
    self._highlight(filename, lbegin, lend)
  File "/home/pmoreau/privat/dotfiles/config/nvim/plugged/chromatica.nvim/rplugin/python3/chromatica/chromatica.py", line 157, in _highlight
    syn_group = syntax.get_highlight(tu, buffer.name, _lbegin, _lend)
  File "/home/pmoreau/privat/dotfiles/config/nvim/plugged/chromatica.nvim/rplugin/python3/chromatica/syntax.py", line 409, in get_highlight
    n_moreline = token.spelling.count("\n")
  File "/home/pmoreau/privat/dotfiles/config/nvim/plugged/chromatica.nvim/rplugin/python3/clang/cindex.py", line 3188, in spelling
    return str(conf.lib.clang_getTokenSpelling(self._tu, self))
  File "/home/pmoreau/privat/dotfiles/config/nvim/plugged/chromatica.nvim/rplugin/python3/clang/cindex.py", line 89, in __str__
    return str(self.value)
  File "/home/pmoreau/privat/dotfiles/config/nvim/plugged/chromatica.nvim/rplugin/python3/clang/cindex.py", line 95, in value
    return super(c_char_p, self).value.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 1: invalid start byte
```

Bisecting the last commits points to 6d374fb479a735effd81142827c41b0b468dee4c being the one introducing the regression.

clang: 3.9.0
neovim: 0.1.7
CMake: 3.6.3

I use CMake to generate the compile_commands.json, which is read by Chromatica. You can find the code I used to trigger the error [here](https://github.com/LUGGPublic/CG_Labs/blob/master/src/core/opengl.cpp).

**Comment by arakashic** [comment]
I am sorry about the problem. It looks like the update of libclang binding was the commit that has the problem. I have reverted the commit for now.

On a side note, I've checked out the code you mentioned and could not reproduce the problem. Can you double check if your system encoding is UTF-8?

**Comment by lasypig** [comment]
这个我也遇到了

**Comment by pierremoreau** [comment]
> Can you double check if your system encoding is UTF-8?

`LANG is` set to `en_GB.UTF-8` and `locale charmap` returns `UTF-8` as well. So, I would assume that it does. Let me check on another computer.
