### ISSUE TITLE
CursorKind is not defined

### ISSUE THREAD

**Issue by duganchen** [arakashic/chromatica.nvim#62]
I can't seem to "UpdateRemotePlugins" with this on my Linux system.

    Encountered NameError loading plugin at /home/dugan/.config/nvim/pack/minpac/start/chromatica.nvim/rplugin/python3/chromatica: name 'CursorKind' is not defined
    Traceback (most recent call last):
      File "/home/dugan/.local/lib64/python3.6/site-packages/pynvim/plugin/host.py", line 135, in _load
        module = imp.load_module(name, file, pathname, descr)
      File "/usr/lib64/python3.6/imp.py", line 245, in load_module
        return load_package(name, filename)
      File "/usr/lib64/python3.6/imp.py", line 217, in load_package
        return _load(spec)
      File "<frozen importlib._bootstrap>", line 684, in _load
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    NameError: name 'CursorKind' is not defined
    remote/host: python3 host registered plugins ['deoplete', 'semshi']
    remote/host: generated rplugin manifest: /home/dugan/.local/share/nvim/rplugin.vim

**Comment by frogzjx** [comment]
:+1:
